ALTER TABLE `form_submissions` ADD `ip_address` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `home_type` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utility_bill` integer;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `credit_score` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `roof_shade` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `solar_reason` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `roof_type` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `project_type` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `landing_page` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `placement` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_source` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_medium` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_campaign` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_term` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_content` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `utm_id` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `fbclid` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `gclid` text;--> statement-breakpoint
ALTER TABLE `form_submissions` ADD `device_category` text;